name: Xamarin.Android.Tools $(Rev:r)

trigger:
  - master
  - d16-*

pr:
  - master
  - d16-*

# Global variables
variables:
  DotNetCoreVersion: 3.1.100
  HostedMac: Hosted Mac Internal
  HostedWinVS2019: Hosted Windows 2019 with VS2019

jobs:
- job: windows
  displayName: windows
  pool: $(HostedWinVS2019)
  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core $(DotNetCoreVersion)
    inputs:
      version: $(DotNetCoreVersion)
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'
    inputs:
      versionSpec: '5.4.x'
  - task: NuGetCommand@2
    displayName: 'NuGet Restore'
    inputs:
      restoreSolution: Xamarin.Android.Tools.sln
  - task: MSBuild@1
    displayName: 'Build solution Xamarin.Android.Tools.sln'
    inputs:
      solution: Xamarin.Android.Tools.sln
  - task: VSTest@2
    displayName: 'Run Tests'
    inputs:
      testAssemblyVer2: 'bin\TestDebug\*-Tests.dll'
  - powershell: |
      $hashOfLastVersionChange = & "git" "log" "--follow" "-1" "--pretty=%H" "nuget.version"
      $commitsSinceVersionChange = & "git" "rev-list" "--count" "$hashOfLastVersionChange..HEAD"
      $majorMinor = Get-Content "nuget.version"
      $version = "$majorMinor.$commitsSinceVersionChange"
      Write-Host "##vso[task.setvariable variable=xat.nuget.version]$version"
  - task: MSBuild@1
    displayName: 'Build NuGet'
    inputs:
      solution: 'src\Xamarin.Android.Tools.AndroidSdk\Xamarin.Android.Tools.AndroidSdk.csproj'
      msbuildArguments: '/t:pack /p:Version=$(xat.nuget.version) /p:OutputPath=$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: Upload Artifacts
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
- job: mac
  displayName: mac
  pool: $(HostedMac)
  steps:
  - task: UseDotNet@2
    displayName: Use .NET Core $(DotNetCoreVersion)
    inputs:
      version: $(DotNetCoreVersion)
  - task: NuGetToolInstaller@1
    displayName: 'Install NuGet'
    inputs:
      versionSpec: '5.4.x'
  - task: NuGetCommand@2
    displayName: 'NuGet Restore'
    inputs:
      restoreSolution: Xamarin.Android.Tools.sln
      restoreDirectory: 'packages'
  - task: MSBuild@1
    displayName: 'Build solution Xamarin.Android.Tools.sln'
    inputs:
      solution: Xamarin.Android.Tools.sln
  - script: mono packages/nunit.consolerunner/3.9.0/tools/nunit3-console.exe bin/TestDebug/Xamarin.Android.Tools.AndroidSdk-Tests.dll
    displayName: Run Tests
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: TestResult.xml
